# Copyright © 2023 The Spray Proxy Contributors
# SPDX-License-Identifier: Apache-2.0

resources:
  - namespace.yaml
  - sprayproxy.yaml
  - route.yaml # only for openshift deployments
  - sprayproxy-rbac.yaml
  - service-monitor.yaml

namespace: sprayproxy
