# Copyright © 2023 The Spray Proxy Contributors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sprayproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-kube-rbac-proxy
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sprayproxy-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sprayproxy-kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: sprayproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-backend-register
rules:
  - nonResourceURLs:
      - "/backends"
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sprayproxy-backend-register
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sprayproxy-backend-register
subjects:
  - kind: ServiceAccount
    name: sprayproxy
    namespace: sprayproxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  annotations:
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sprayproxy-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sprayproxy-metrics-reader
subjects:
  - kind: ServiceAccount
    name: metrics-reader
